-- Phase G: role/service curation foundation (lean)

-- 1) Extend source_type enum to support explicit AI inferred semantics.
do $$
begin
  if not exists (
    select 1
    from pg_enum e
    join pg_type t on t.oid = e.enumtypid
    where t.typname = 'source_type_enum'
      and e.enumlabel = 'ai_inferred'
  ) then
    alter type public.source_type_enum add value 'ai_inferred';
  end if;
end $$;

-- 2) Establishment role curation fields (low footprint, high signal).
alter table public.establishments
  add column if not exists store_roles text[] not null default array['unclear']::text[],
  add column if not exists store_role_primary text not null default 'unclear',
  add column if not exists role_confidence numeric(5,4),
  add column if not exists role_classification_method text,
  add column if not exists role_classified_at timestamptz,
  add column if not exists is_relevant_for_kiezkauf boolean not null default true,
  add column if not exists manual_review_status text not null default 'pending',
  add column if not exists manual_review_notes text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'establishments_store_roles_chk'
  ) then
    alter table public.establishments
      add constraint establishments_store_roles_chk
      check (
        store_roles <@ array[
          'sells_physical_products',
          'sells_services',
          'repair_service',
          'food_prepared',
          'food_grocery',
          'health_care',
          'beauty_personal_care',
          'specialist_retail',
          'unclear'
        ]::text[]
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'establishments_store_role_primary_chk'
  ) then
    alter table public.establishments
      add constraint establishments_store_role_primary_chk
      check (
        store_role_primary in (
          'sells_physical_products',
          'sells_services',
          'repair_service',
          'food_prepared',
          'food_grocery',
          'health_care',
          'beauty_personal_care',
          'specialist_retail',
          'unclear'
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'establishments_manual_review_status_chk'
  ) then
    alter table public.establishments
      add constraint establishments_manual_review_status_chk
      check (manual_review_status in ('pending', 'approved', 'rejected', 'not_needed'));
  end if;
end $$;

create index if not exists idx_establishments_store_role_primary
  on public.establishments(store_role_primary);

create index if not exists idx_establishments_store_roles_gin
  on public.establishments using gin(store_roles);

create index if not exists idx_establishments_manual_review_pending
  on public.establishments(updated_at asc)
  where manual_review_status = 'pending';

-- 3) Canonical services + aliases (lean, similar to product model).
create table if not exists public.canonical_services (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  display_name_en text not null,
  display_name_de text,
  display_name_es text,
  group_key text not null default 'services',
  coverage_tier text not null default 'core',
  priority integer not null default 60,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint canonical_services_slug_not_blank_chk check (char_length(btrim(slug)) > 0),
  constraint canonical_services_coverage_tier_chk check (coverage_tier in ('core', 'extended', 'edge')),
  constraint canonical_services_priority_range_chk check (priority between 0 and 100)
);

create index if not exists idx_canonical_services_group_priority
  on public.canonical_services(group_key, coverage_tier, priority desc)
  where is_active = true;

create table if not exists public.canonical_service_aliases (
  id bigint generated by default as identity primary key,
  canonical_service_id bigint not null references public.canonical_services(id) on delete cascade,
  lang text not null default 'de',
  alias text not null,
  alias_normalized text generated always as (lower(regexp_replace(btrim(alias), '\\s+', ' ', 'g'))) stored,
  priority integer not null default 50,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint canonical_service_aliases_lang_chk check (lang in ('de', 'en', 'es', 'any')),
  constraint canonical_service_aliases_alias_not_blank_chk check (char_length(alias_normalized) > 0),
  constraint canonical_service_aliases_priority_range_chk check (priority between 0 and 100),
  constraint canonical_service_aliases_unique unique (canonical_service_id, lang, alias_normalized)
);

create index if not exists idx_canonical_service_aliases_lookup
  on public.canonical_service_aliases(lang, alias_normalized)
  where is_active = true;

create index if not exists idx_canonical_service_aliases_alias_trgm
  on public.canonical_service_aliases using gin (alias_normalized gin_trgm_ops)
  where is_active = true;

-- 4) Service candidates + merged serving layer.
create table if not exists public.establishment_service_candidates (
  id bigint generated by default as identity primary key,
  establishment_id bigint not null references public.establishments(id) on delete cascade,
  canonical_service_id bigint not null references public.canonical_services(id) on delete cascade,
  source_type public.source_type_enum not null,
  generation_method text not null,
  confidence numeric(5,4) not null,
  validation_status public.validation_status_enum not null default 'unvalidated',
  availability_status text not null default 'likely',
  validation_notes text,
  why_this_service_matches text,
  inferred_from jsonb not null default '{}'::jsonb,
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint esc_confidence_range_chk check (confidence between 0 and 1),
  constraint esc_availability_status_chk check (availability_status in ('confirmed', 'likely', 'unknown', 'rejected')),
  constraint esc_unique unique (establishment_id, canonical_service_id, source_type, generation_method)
);

create index if not exists idx_esc_establishment_confidence
  on public.establishment_service_candidates(establishment_id, confidence desc);

create index if not exists idx_esc_validation_status
  on public.establishment_service_candidates(validation_status);

create table if not exists public.establishment_service_merged (
  id bigint generated by default as identity primary key,
  establishment_id bigint not null references public.establishments(id) on delete cascade,
  canonical_service_id bigint not null references public.canonical_services(id) on delete cascade,
  primary_source_type public.source_type_enum not null,
  merged_sources public.source_type_enum[] not null default array[]::public.source_type_enum[],
  merged_candidate_ids bigint[] not null default array[]::bigint[],
  confidence numeric(5,4) not null,
  validation_status public.validation_status_enum not null,
  availability_status text not null default 'likely',
  why_this_service_matches text,
  source_url text,
  updated_at timestamptz not null default now(),
  constraint esm_confidence_range_chk check (confidence between 0 and 1),
  constraint esm_availability_status_chk check (availability_status in ('confirmed', 'likely', 'unknown', 'rejected')),
  constraint esm_unique unique (establishment_id, canonical_service_id)
);

create index if not exists idx_esm_establishment
  on public.establishment_service_merged(establishment_id);

create index if not exists idx_esm_service
  on public.establishment_service_merged(canonical_service_id);

create index if not exists idx_esm_validation_status
  on public.establishment_service_merged(validation_status);

-- 5) Long-tail query lexicon and failed searches (lean, actionable).
create table if not exists public.canonical_search_terms (
  id bigint generated by default as identity primary key,
  canonical_type text not null,
  canonical_product_id bigint references public.canonical_products(id) on delete cascade,
  canonical_service_id bigint references public.canonical_services(id) on delete cascade,
  canonical_term text not null,
  lang text not null default 'any',
  aliases text[] not null default array[]::text[],
  related_store_roles text[] not null default array[]::text[],
  priority integer not null default 50,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cst_canonical_type_chk check (canonical_type in ('product', 'service')),
  constraint cst_lang_chk check (lang in ('de', 'en', 'es', 'any')),
  constraint cst_priority_range_chk check (priority between 0 and 100),
  constraint cst_term_not_blank_chk check (char_length(btrim(canonical_term)) > 0),
  constraint cst_target_ref_chk check (
    (canonical_type = 'product' and canonical_product_id is not null and canonical_service_id is null)
    or
    (canonical_type = 'service' and canonical_service_id is not null and canonical_product_id is null)
  )
);

create index if not exists idx_cst_term_lookup
  on public.canonical_search_terms(lang, lower(canonical_term), priority desc)
  where is_active = true;

create index if not exists idx_cst_aliases_gin
  on public.canonical_search_terms using gin (aliases)
  where is_active = true;

create table if not exists public.failed_searches (
  id bigint generated by default as identity primary key,
  query text not null,
  normalized_query text generated always as (lower(regexp_replace(btrim(query), '\\s+', ' ', 'g'))) stored,
  postcode text,
  district text,
  lat double precision,
  lon double precision,
  radius_meters integer,
  result_count integer not null default 0,
  reason text,
  endpoint text,
  source text not null default 'search_api',
  resolved boolean not null default false,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  constraint failed_searches_query_not_blank_chk check (char_length(btrim(query)) > 0)
);

create index if not exists idx_failed_searches_recent
  on public.failed_searches(created_at desc);

create index if not exists idx_failed_searches_normalized
  on public.failed_searches(normalized_query);

create index if not exists idx_failed_searches_unresolved
  on public.failed_searches(created_at desc)
  where resolved = false;

-- 6) Updated-at triggers.
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_canonical_services_set_updated_at') then
    create trigger trg_canonical_services_set_updated_at
      before update on public.canonical_services
      for each row execute function public.set_updated_at_timestamp();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_canonical_service_aliases_set_updated_at') then
    create trigger trg_canonical_service_aliases_set_updated_at
      before update on public.canonical_service_aliases
      for each row execute function public.set_updated_at_timestamp();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_esc_set_updated_at') then
    create trigger trg_esc_set_updated_at
      before update on public.establishment_service_candidates
      for each row execute function public.set_updated_at_timestamp();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_esm_set_updated_at') then
    create trigger trg_esm_set_updated_at
      before update on public.establishment_service_merged
      for each row execute function public.set_updated_at_timestamp();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_cst_set_updated_at') then
    create trigger trg_cst_set_updated_at
      before update on public.canonical_search_terms
      for each row execute function public.set_updated_at_timestamp();
  end if;
end $$;

-- 7) RLS and grants.
alter table if exists public.canonical_services enable row level security;
alter table if exists public.canonical_service_aliases enable row level security;
alter table if exists public.establishment_service_candidates enable row level security;
alter table if exists public.establishment_service_merged enable row level security;
alter table if exists public.canonical_search_terms enable row level security;
alter table if exists public.failed_searches enable row level security;

revoke all on table public.canonical_services from anon, authenticated;
revoke all on table public.canonical_service_aliases from anon, authenticated;
revoke all on table public.establishment_service_candidates from anon, authenticated;
revoke all on table public.establishment_service_merged from anon, authenticated;
revoke all on table public.canonical_search_terms from anon, authenticated;
revoke all on table public.failed_searches from anon, authenticated;

grant select on table public.canonical_services to anon, authenticated;
grant select on table public.canonical_service_aliases to anon, authenticated;
grant select on table public.establishment_service_merged to anon, authenticated;
grant select on table public.canonical_search_terms to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'canonical_services' and policyname = 'public_read_canonical_services'
  ) then
    create policy public_read_canonical_services
      on public.canonical_services
      for select
      using (is_active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'canonical_service_aliases' and policyname = 'public_read_canonical_service_aliases'
  ) then
    create policy public_read_canonical_service_aliases
      on public.canonical_service_aliases
      for select
      using (is_active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'establishment_service_merged' and policyname = 'public_read_establishment_service_merged'
  ) then
    create policy public_read_establishment_service_merged
      on public.establishment_service_merged
      for select
      using (validation_status <> 'rejected');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'canonical_search_terms' and policyname = 'public_read_canonical_search_terms'
  ) then
    create policy public_read_canonical_search_terms
      on public.canonical_search_terms
      for select
      using (is_active = true);
  end if;
end $$;

-- 8) Lean core seed for services.
insert into public.canonical_services (slug, display_name_en, display_name_de, display_name_es, group_key, coverage_tier, priority)
values
  ('phone-repair', 'Phone repair', 'Handy Reparatur', 'Reparacion de movil', 'repair', 'core', 95),
  ('computer-repair', 'Computer repair', 'Computer Reparatur', 'Reparacion de ordenador', 'repair', 'core', 90),
  ('bike-repair', 'Bike repair', 'Fahrrad Reparatur', 'Reparacion de bicicleta', 'repair', 'core', 92),
  ('shoe-repair', 'Shoe repair', 'Schuhreparatur', 'Reparacion de zapatos', 'repair', 'core', 86),
  ('tailoring', 'Tailoring / alterations', 'Schneiderei', 'Arreglos de ropa', 'services', 'core', 85),
  ('key-cutting', 'Key cutting', 'Schluesseldienst', 'Copia de llaves', 'services', 'core', 94),
  ('watch-battery-replacement', 'Watch battery replacement', 'Batteriewechsel Uhr', 'Cambio de pila de reloj', 'services', 'core', 76),
  ('dry-cleaning', 'Dry cleaning', 'Reinigung', 'Tintoreria', 'services', 'core', 82),
  ('copy-print', 'Copy & print', 'Copyshop', 'Copisteria e impresion', 'services', 'core', 80),
  ('pedicure', 'Pedicure', 'Pedikuere', 'Pedicura', 'beauty', 'extended', 70),
  ('manicure', 'Manicure', 'Manikuere', 'Manicura', 'beauty', 'extended', 68)
on conflict (slug)
do update set
  display_name_en = excluded.display_name_en,
  display_name_de = excluded.display_name_de,
  display_name_es = excluded.display_name_es,
  group_key = excluded.group_key,
  coverage_tier = excluded.coverage_tier,
  priority = excluded.priority,
  updated_at = now();

insert into public.canonical_service_aliases (canonical_service_id, lang, alias, priority)
select s.id, a.lang, a.alias, a.priority
from public.canonical_services s
join (
  values
    ('phone-repair', 'en', 'phone repair', 90),
    ('phone-repair', 'en', 'screen repair', 88),
    ('phone-repair', 'de', 'handy reparatur', 95),
    ('phone-repair', 'de', 'display reparatur', 88),
    ('phone-repair', 'es', 'reparacion movil', 86),
    ('computer-repair', 'en', 'laptop repair', 90),
    ('computer-repair', 'de', 'laptop reparatur', 92),
    ('bike-repair', 'en', 'bike repair', 92),
    ('bike-repair', 'de', 'fahrrad reparatur', 95),
    ('shoe-repair', 'de', 'schuhreparatur', 92),
    ('tailoring', 'de', 'schneiderei', 95),
    ('tailoring', 'en', 'alterations', 88),
    ('key-cutting', 'de', 'schluesseldienst', 95),
    ('key-cutting', 'en', 'key cutting', 95),
    ('copy-print', 'de', 'copyshop', 95),
    ('copy-print', 'en', 'printing', 78),
    ('dry-cleaning', 'de', 'reinigung', 92),
    ('dry-cleaning', 'en', 'dry cleaning', 92),
    ('pedicure', 'de', 'pedikuere', 95),
    ('pedicure', 'en', 'pedicure', 95)
) a(slug, lang, alias, priority)
  on a.slug = s.slug
on conflict on constraint canonical_service_aliases_unique
 do update set
   priority = greatest(public.canonical_service_aliases.priority, excluded.priority),
   is_active = true,
   updated_at = now();
